### ISSUE TITLE
Can't set up a cluster - connection refused.

### ISSUE THREAD

**Issue by buzzwordy** [kube-hetzner/terraform-hcloud-kube-hetzner#138]
Hi,
trying to set up a cluster, but the script fails with the following error:

```
module.agents["agent-large-1"].hcloud_server.server: Still creating... [6m50s elapsed]
module.control_planes[0].hcloud_server.server: Still creating... [6m50s elapsed]
module.control_planes[1].hcloud_server.server: Still creating... [6m50s elapsed]
module.control_planes[2].hcloud_server.server: Still creating... [7m0s elapsed]
module.control_planes[0].hcloud_server.server: Still creating... [7m0s elapsed]
module.control_planes[1].hcloud_server.server: Still creating... [7m0s elapsed]
╷
│ Error: remote-exec provisioner error
│ 
│   with module.agents["agent-large-1"].hcloud_server.server,
│   on modules/host/main.tf line 70, in resource "hcloud_server" "server":
│   70:   provisioner "remote-exec" {
│ 
│ timeout - last error: dial tcp xxx.xxx.xxx.xxx:22: connect: connection refused

 Error: remote-exec provisioner error
│ 
│   with module.control_planes[0].hcloud_server.server,
│   on modules/host/main.tf line 70, in resource "hcloud_server" "server":
│   70:   provisioner "remote-exec" {
│ 
│ timeout - last error: dial tcp xxx.xxx.xxx.xxx:22:: connect: connection refused
```

Seems that it can't connect to the nodes via ssh.

**Comment by phaer** [comment]
Hi @buzzwordy! Can you connect to the server manually using `ssh` or does it time out as well?

If you can, please try to reproduce with `TF_LOG=debug terraform apply` and see if that helps figuring out - feel free to paste the log file (in a [detail tag](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) please ;)) if it does not!

**Comment by buzzwordy** [comment]
No, I can't connect from console as well.
`1mmodule.control_planes[0].hcloud_server.server (local-exec):[0m [0mWaiting for MicroOS to reboot and become available...`
 It stucks after the machines reboot. That's for both - control plane and agent nodes.

**Comment by phaer** [comment]
Did you try activate [debug logging](https://www.terraform.io/internals/debugging) as suggested above? I think that would be the best approach to find out what went wrong.

Because the `remote-exec` provisioner at line 70 seems to fail, but terraform should not even get to that point unless your workstation was able to connect in the `local-exec` provisioner at [line 60](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/modules/host/main.tf#L60).

Could be that the timing of the reboot hack is off or something? But I think we need more info before being able to help here :)

**Comment by mysticaltech** [comment]
@buzzwordy It's probably just an issue with your SSH keys, just generate new ed25519 ones without a passphrase and try again.

**Comment by buzzwordy** [comment]
Problem solved - the issue was the wrong type of SSH key.  Thanks for all the help.
