### ISSUE TITLE
Control plane loadbalancer

### ISSUE THREAD

**Issue by HenkVanMaanen** [kube-hetzner/terraform-hcloud-kube-hetzner#143]
How is the control plane HA? I don't see a loadbalancer for the control plane nodes. E.g. the agents connect to the first node, what happens if the first node goes offline?

**Comment by mysticaltech** [comment]
The cluster becomes HA when the control planes nodes number is equal or superior to 3, and always odd numbers as advised by Rancher.

When you have 3 control plane nodes, you can take any of them offline, and the cluster will continue to work. That is what happens when the automatic upgrades of both OS and k3s happen.

Now, if you are talking of using kubectl in an HA manner, that is not implemented. We use the IP of the first control plane in the `kubeconfig.yaml`. However, if it is not reachable, you can swipe it for other IPs of other control planes manually. But normally, control plane nodes go offline for a few seconds max for a reboot.

If you have a better solution for that, please propose it.

**Comment by HenkVanMaanen** [comment]
Ah that clears some things up. I thought that you needed a loadbalancer to make the control plane HA. Didn't know that under the hood the agents themselves talk to all 3 control plane nodes. 

Kubectl HA is not a priority for me now but if somebody else wants to fix it, here are some general pointers:

* Hetzner loadbalancer pointing to all control plane nodes
* Kubeconfig must contain loadbalancer public ip instead of control plane ip
* Control plane nodes need to be initialized with the following extra flags:
  * `--tls-san ${lb_private_ip}`
  * `--tls-san ${lb_public_ip}`

**Comment by codeagencybe** [comment]
@mysticaltech 

You might want to check this example from TechnoTim his Youtube channel. 
He solves the controlplane HA with Kubevip and MetalLB. Don't know if this is something easy to introduce in your setup, but this takes care of auto-updating the IP
https://www.youtube.com/watch?v=CbkEWcUZ7zM

Another solution would be to add KeepAlived with 2 extra nodes and a floating IP which in return route traffic to 1 of the 3 control nodes that are healthy. If they go down, it routes to 2nd or 3rd one. 
This method does add 2 extra node as cost

**Comment by HenkVanMaanen** [comment]
I think those articles about Keepalived are because in that time Hetzner did not have loadbalancers yet. This problem can be solved using their loadbalancers IMO

**Comment by mysticaltech** [comment]
Exactly... Maybe something like that would work. But really, it's almost a nonissue. If you ever were to try to kubectl into a node that is being rebooted or down, you would change the IP in the kubeconfig.yaml file manually to the next control plane node.

So unless you folk need this, we can close the issue.
