### ISSUE TITLE
Adding/changing labels and taints have no effect when running the plan again

### ISSUE THREAD

**Issue by otavio** [kube-hetzner/terraform-hcloud-kube-hetzner#227]
If a cluster is defined, it cannot have taints and labels added or changed.

**Comment by mysticaltech** [comment]
@otavio This is expected, I will clarify it in the docs. Not everything can be changed once the cluster is up and running.

**Comment by otavio** [comment]
Couldn't it be reworked using the kubectl? so it'll allow the provisioning to keep it in a consistent state. Or do you see some problem in doing it?

**Comment by mysticaltech** [comment]
The thing is - If it doesn't touch Hetzner, there is no need to do it through our terraform provider. As you said, it can be done through kubectl or even probably the [Kubernetes terraform provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs). 

I fully understand the need to keep state; that's why we built `Kube-Hetzner` as a module. Now, I would be curious if you see an easy fix that would allow the labels to be re-applied. But it seems out of scope for me. Yes, setting an initial state is okay because we have an opportunity to do so, but later, what is well supported is adding and removing nodes.

@phaer @mnencia What do you think?

**Comment by mysticaltech** [comment]
@otavio I will make sure to update the docs. Thanks for this precision, it's indeed important that our users know what to expect.

**Comment by HenkVanMaanen** [comment]
@otavio Maybe you could have a look at https://github.com/xunleii/terraform-module-k3s/blob/master/server_nodes.tf#L265 

And create a PR if you really wanted this functionality :)

**Comment by otavio** [comment]
In fact, kube-hetzner could use the module and avoid duplicating the effort.

**Comment by mysticaltech** [comment]
@otavio We won't add a dependency on another module at this point, but as @HenkVanMaanen said, PRs are always welcome to add the functionality you want!

**Comment by mysticaltech** [comment]
Closing this as "not planned", but as said above, contributions are always welcome!
