### ISSUE TITLE
Changing the DNS server leads to unroutable storage box

### ISSUE THREAD

**Issue by PurpleBooth** [kube-hetzner/terraform-hcloud-kube-hetzner#249]
When the DNS servers are changed it leads to the storage box product being unreachable, as the IPv6 address they are connectable on is different when using the Hetzner provided DNS and the Google/Cloudflare ones.

Woud you be open to a pull request making, defaulting to on, the DNS server change optional?

**Comment by mysticaltech** [comment]
@PurpleBooth We don't have official support for IPv6 yet! 

If you want to contribute a PR, it would be most welcome.

**Comment by PurpleBooth** [comment]
Cool, will submit something in the upcoming days. Thanks

**Comment by mysticaltech** [comment]
Please explain more, and share your kube.tf without the sensitive values if you can.

**Comment by phaer** [comment]
@mysticaltech As I understand it:

We are currently using Googles & Cloudflares public DNS servers for nodes (see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/81e73580db795484c00ed0a1dadc836cd0e437f8/modules/host/templates/userdata.yaml.tpl#L57). 

Hetzner runs its own DNS Servers (https://docs.hetzner.com/dns-console/dns/general/authoritative-name-servers) which seem to announce different IPs for some of their services (e.g. the "storage box") than other DNS servers do. At least on ipv6, probably on ipv4 as well.

So two issues
* ipv6 support: we don't need much. ingress via ipv6 is already working if using hetzner load balancers. Egress traffic to (some?) ipv6 addresses seems to be broken.
* custom dns servers: we should either allow users two customize used DNS servers and/or default to hetzners instead of Google & Cloudflare. 

is this correct @PurpleBooth? Would your PR address both of this issues? We don't have much maintainer bandwidth available atm to implement feature requests ourselves, but try to help new contributors where we can :)

**Comment by PurpleBooth** [comment]
This is spot on @phaer!

**Comment by mysticaltech** [comment]
Awesome @phaer. Thanks for the clear explanation!

**Comment by PurpleBooth** [comment]
Closing in favour of the PR
