### ISSUE TITLE
HELM Deployment Traefik Crashloop

### ISSUE THREAD

**Issue by cur1ou5soul** [kube-hetzner/terraform-hcloud-kube-hetzner#377]
My Helm-Deployment is in state CrashLoop, here are the last logs:

` grep -q -e 'https\?://'
+ echo 'chart path is a url, skipping repo update'
+ helm_v3 repo remove stable
chart path is a url, skipping repo update
Error: no repositories configured
+ true
+ return
+ helm_update install --set-string global.systemDefaultRegistry=
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^traefik$' --namespace kube-system --output json
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=2.9.1,failed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ 2.9.1 =~ ^(|null)$ ]]
+ [[ failed =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ failed == \d\e\p\l\o\y\e\d ]]
+ [[ failed =~ ^(deleted|failed|null|unknown)$ ]]
+ [[ abort == \r\e\i\n\s\t\a\l\l ]]
+ echo 'Release status is '\''failed'\'' and failure policy is '\''abort'\'', not '\''reinstall'\''; waiting for operator intervention'
Release status is 'failed' and failure policy is 'abort', not 'reinstall'; waiting for operator intervention
+ echo 'Release status is '\''failed'\'' and failure policy is '\''abort'\'', not '\''reinstall'\''; waiting for operator intervention'
+ exit 1`

**Comment by mysticaltech** [comment]
@cur1ou5soul The Traefik automatic upgrade is failing and just requires manual intervention. Because in that instance, to upgrade, it needs to reinstall, which we do not allow without user intervention, as it could change the value of the LB IP. 

You can grab the manifest with `kubectl get helmchartconfig ... -o yaml`. 

So we have in traefik HelmChartConfig this param set `failurePolicy: abort`, just change "abort" to "reinstall". You can even use kubectl edit to do it!

Then force the update manually (so you do not have to wait) with: `curl https://github.com/k3s-io/k3s/blob/master/manifests/traefik.yaml | kubectl apply -f -`.

Then, when the upgrade is done (check if all helm jobs have been completed successfully), put back the failure policy to "abort". 

Please not that this upgrade will probably give a new LB IP to the Traefik ingress controller, so update your DNS accordingly. That's why we prefer to abort by default, as not to break your system by having the IP change without you knowing!

**Comment by mysticaltech** [comment]
_If you prefer to not have to deal with that every once in a while, you can use ingress-nginx instead, which we support, just by setting `enable_traefik=false` and `enable_nginx=true` in your kube.tf._
