### ISSUE TITLE
 remote-exec provisioner error while appying terraform script

### ISSUE THREAD

**Issue by Biacode** [kube-hetzner/terraform-hcloud-kube-hetzner#414]
I am getting an error while applying terraform script.
See error message.
```
╷
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.kustomization,
│   on .terraform/modules/kube-hetzner/init.tf line 232, in resource "null_resource" "kustomization":
│  232:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_709453228.sh": Process exited with status 124
╵

```
After which, I can observe many load balancers createdin hcloud. See the screenshot.

![image](https://user-images.githubusercontent.com/10510996/201762157-665b125c-714f-4026-b87e-47b8fb525c4d.png)

**Comment by mysticaltech** [comment]
@Biacode Everything looks kosher! IMHO, just terraform destroy (see readme), and make sure that your project is empty, and try again.

**Comment by Biacode** [comment]
Hey @mysticaltech, I did this countless times already :)
Destroy, re-create, and many tries.
The funny thing is, previously, I didn't have such an issue, around 1-2 days ago. Within the same config, the same empty dir.

**Comment by mysticaltech** [comment]
Considering this solved.

**Comment by codeagencybe** [comment]
Has this problem been solved? 
Because I'm seeing exactly same problem. 
1. my LB's are not showing up both. Only 1 is generated (controlplanes only) the other one is not showing up anymore
2. terraform output is running extremely long trying to remote-exec something


```
module.kube-hetzner.null_resource.kustomization: Still creating... [23m50s elapsed]
module.kube-hetzner.null_resource.kustomization (remote-exec): Waiting for load-balancer to get an IP...
```

Then resulting into

```
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.kustomization,
│   on .terraform/modules/kube-hetzner/init.tf line 232, in resource "null_resource" "kustomization":
│  232:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_910558601.sh": Process exited with status 124
```
1. We didn't apply anything kustomization
2. nothing is enabled that uses anything from this either


In the list of resources, we also see it's creating autoscaler nodes? 
Why? This behaviour was not before < v1.6.5 (previous cluster was created wiht 1.6.3 and did just fine)
We also saw in a test it was generating at some point 5 control plane nodes? The maximum was 3, why it turn up 5? 

A. yes we did restart from scratch (create new project in Hetzner, take new token, etc... same result)
B. yes everything is up to date for hcloud and terraform

There is clearly something wrong with v 1.6.5 that is doing random stuff with load balancer and auto scaling that should not be happening. 

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/7568546/202673741-ffa464d5-b26e-4878-a3ea-40027bd9ca43.png">

**Comment by ifeulner** [comment]
Hi @codeagencybe the autoscaler nodes will be only created if you have defined them in your kube.tf. They should not appear "just by accident"?

**Comment by codeagencybe** [comment]
yes I did create them but they are set with minimum ZERO and maximum 5
There is no load at all, no apps deployed, so where is the logic that out of nothing suddenly 2 AS nodes are showing up? 

I have created an AS pool in all 3 regio by the way, so if this was consistent, then it would turn up 1 in each regio
Instead I get random 1 or 2

Also, I have 3 control planes set, but I sometimes get 4 or even 5 control planes!?!
This also never happened in previous releases. 

Also my load balancer is missing. I have enabled   use_control_plane_lb = true so this should result in 2 LB's, but I only get 1. 

When I go back to v1.6.3, nothing of these problems happen. 
I get my 2 LB's instantly, no random AS nodes showing up either. 

I started from scratch, new project, new token, everything new, and I can repeat these problems over and over. Just like other people confirmed IDENTICAL error like I reported. That's not coincidence. 
The latest release is just broken, simple as that.

**Comment by codeagencybe** [comment]
Here's my kube.tf
```

  control_plane_nodepools = [
    {
      name        = "CP-fsn1",
      server_type = "cpx31",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "CP-nbg1",
      server_type = "cpx31",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "CP-hel1",
      server_type = "cpx31",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "CPX51-fsn1",
      server_type = "cpx51",
      location    = "fsn1",
      labels      = [],
      # To exclude from Longhorn if that is used for instance. Completely optional.
      taints = [
        "server-usage=storage:NoSchedule"
      ],
      count       = 1
    },
        {
      name        = "CPX51-nbg1",
      server_type = "cpx51",
      location    = "nbg1",
      labels      = [],
      # To exclude from Longhorn if that is used for instance. Completely optional.
      taints = [
        "server-usage=storage:NoSchedule"
      ],
      count       = 1
    },
        {
      name        = "CPX51-hel1",
      server_type = "cpx51",
      location    = "hel1",
      labels      = [],
      # To exclude from Longhorn if that is used for instance. Completely optional.
      taints = [
        "server-usage=storage:NoSchedule"
      ],
      count       = 1
    }
  ]

  load_balancer_type     = "lb31"
  load_balancer_location = "fsn1"


  autoscaler_nodepools = [
    {
      name        = "AS-fsn1"
      server_type = "cpx51" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "fsn1"
      min_nodes   = 0
      max_nodes   = 5
    },
    {
      name        = "AS-nbg1"
      server_type = "cpx51" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "nbg1"
      min_nodes   = 0
      max_nodes   = 5
    },
    {
      name        = "AS-hel1"
      server_type = "cpx51" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "hel1"
      min_nodes   = 0
      max_nodes   = 5
    }
  ]

```

**Comment by ifeulner** [comment]
This could happen if the some pods cannot be scheduled, e.g. if the load balancer does not work it could also be that some load could not be scheduled. Then the autoscaler tries to bring up some new nodes to address this. So I think it's a chain reaction and the core problem is the loadbalancer that is fully available.

**Comment by codeagencybe** [comment]
> This could happen if the some pods cannot be scheduled, e.g. if the load balancer does not work it could also be that some load could not be scheduled. Then the autoscaler tries to bring up some new nodes to address this. So I think it's a chain reaction and the core problem is the loadbalancer that is fully available.

That's exactly what I also think. 
Because multiple people are already confirming the same LB issues since a few days, I suspect this is just cascading building on top of the LB problem. 


About the taints, I didn't set those. This is exactly how the example kube.tf in the repo give it to use. 
If those taints are not good, then in all honestly they shouldn't be set as default. 
The base example kube.tf should be a minimal working example "out of the box". 
Add or change things to your likings, but at least the base should give a working set.

**Comment by mysticaltech** [comment]
@codeagencybe It's this taint causing it  "server-usage=storage:NoSchedule", as pods are not able to be scheduled. This has been removed from the current docs.
