### ISSUE TITLE
[Feature Request]: Inject token to cloud-init using env var

### ISSUE THREAD

**Issue by gthieleb** [kube-hetzner/terraform-hcloud-kube-hetzner#601]
### Description

When using hcloud token via envvar (as described in #599) the token is currently not injected in cloudinit. 

Background: Hetzner does not offer an approach similar to AWS IAM instance role so we need to ship the token ourself.

We should think aboout a way to use an envvar and be able to inject the token anyway.

**Comment by mysticaltech** [comment]
@gthieleb Does that mean that setting HCLOUD_TOKEN alone is not enough to successfully deploy? 

Because if so, we could just rename it TF_VAR_hcloud_token and [it would automatically be picked up](https://support.hashicorp.com/hc/en-us/articles/4547786359571-Reading-and-using-environment-variables-in-Terraform-runs). Please let me know so that I do the change to the kube.tf.

**Comment by mysticaltech** [comment]
@gthieleb I when ahead an renamed the env variable to use to `TF_VAR_hcloud_token`, all you be fixed and that FR handled too! Please let me know if not.

See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kube.tf.example
