### ISSUE TITLE
[Feature Request]:  Configure LB type for API vs Services differently

### ISSUE THREAD

**Issue by supernovae** [kube-hetzner/terraform-hcloud-kube-hetzner#900]
### Description

I'd like to configure the API load balancer to be smaller than the ingress load balancer, but it appears that defining the ingress load balancer size sets it for API too.

If you enable enable use_control_plane_lb, you should be able to define a  control_plane_lb_type

If i have time, i'll try and get a PR if this sounds acceptable. (unless i missed a value to pass something like this already)

**Comment by mysticaltech** [comment]
@supernovae You are right! I would argue that the type of control_plane_lb could be hardcoded to lb11, because it would surprise me anyone need more. BUT we never know, so giving the possibility to choose the lb kind here would be better. Normally that's a very quick modification. PR most welcome! 🙏

**Comment by supernovae** [comment]
Here is the PR https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/901

**Comment by mysticaltech** [comment]
Released in v2.3.2 🥳
